<?php
	function gestorErrors($errno, $errstr, $errfile, $errline) {
		throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
	}
	
	set_error_handler("gestorErrors");

	try {
		//throw new Exception("S'ha produÃ¯t una excepciÃ³");
		//trigger_error("S'ha produÃ¯t un error"); 
		$a = 10/0;
	} catch (Error $e) {
		// ğŸ”¹ Mostra un missatge segur a l'usuari
		echo "S'ha produÃ¯t un Error.<br>";
	} catch (Exception $e) {
		// ğŸ”¹ Mostra un missatge segur a l'usuari
		echo "S'ha produÃ¯t una Exception.<br>";
	} finally {
		// ğŸ”¹ Registre complet al fitxer de log
		$logMessage = "[" . date('Y-m-d H:i:s') . "] "
					. $e->getMessage()
					. " in " . $e->getFile()
					. " on line " . $e->getLine() . PHP_EOL;

		error_log($logMessage, 3, __DIR__ . "/error_log.txt");
	}
?>